print("Escoge una cancion de la siguiente lista, ingresando su respectivo numero:")
print("1. The Beatles - Hey Jude")
print("2. Oasis - Wonderwall")
print("3. Queen - Bohemian Rhapsody")
print("4. The Beatles - Yesterday")
print("5. Pink Floyd - Time")
print("6. The Beatles - Do you want to know a secret")
print("7. Andy Williams - It's the most wonderful time of the year")
print("8. Last Christmas - Wham!")
print("9. Oasis - Don't look back in anger")
print("10. Oasis - Stop crying your heart out\n")

userPick = int(input("Ingresa el numero de la cancion que quieres: "))
print("")
if userPick == 1:
    print("Hey Jude, don't make it bad")
    print("Take a sad song and make it better")
    print("Remember to let her into your heart")
    print("Then you can start to make it better")
    print("Hey Jude, don't be afraid")
    print("You were made to go out and get her")
    print("The minute you let her under your skin")
    print("Then you begin to make it better")
if userPick == 2:
    print("Today is gonna be the day that they're gonna throw it back to you")
    print("By now you should've somehow realized what you gotta do")
    print("I don't believe that anybody feels the way I do, about you now")
    print("Backbeat, the word was on the street that the fire in your heart is out")
    print("I'm sure you've heard it all before but you never really had a doubt")
    print("I don't believe that anybody feels the way I do, about you now")
if userPick == 3:
    print("Is this the real life?")
    print("Is this just fantasy?")
    print("Caught in a landslide")
    print("No escape from reality")
    print("Open your eyes")
    print("Look up to the skies and see")
    print("I'm just a poor boy, I need no sympathy")
    print("Because I'm easy come, easy go")
    print("Little high, little low")
    print("Anyway the wind blows doesn't really matter to me, to me")
if userPick == 4:
    print("Yesterday")
    print("All my troubles seemed so far away")
    print("Now it looks as though they're here to stay")
    print("Oh, I believe in yesterday")
    print("Suddenly")
    print("I'm not half the man I used to be")
    print("There's a shadow hanging over me")
    print("Oh, yesterday came suddenly")
    print("Why she had to go, I don't know")
    print("She wouldn't say")
    print("I said something wrong")
    print("Now I long for yesterday")
if userPick == 5:
    print("Ticking away the moments that make up a dull day")
    print("Fritter and waste the hours in an offhand way")
    print("Kickin' around on a piece of ground in your home town")
    print("Waiting for someone or something to show you the way")
    print("Tired of lying in the sunshine staying home to watch the rain")
    print("You are young and life is long and there is time to kill today")
    print("And then one day you find ten years have got behind you")
    print("No one told you when to run, you missed the starting gun")
if userPick == 6:
    print("You'll never know how much i really love you")
    print("You'll never know how much i really care")
    print("Listen")
    print("Do you want to know a secret?")
    print("Do you promise not to tell?")
    print("Closer")
    print("Let me whisper in your ear")
    print("Say the words you long to hear")
    print("I'm in love with you")
if userPick == 7:
    print("It's the most wonderful time of the year")
    print("With the kids jingle belling")
    print("And everyone telling you be of good cheer")
    print("It's the most wonderful time of the year")
    print("It's the hap-happiest season of all")
    print("With those holiday greetings and gay happy meetings")
    print("When friends come to call")
    print("It's the hap-happiest season of all")
if userPick == 8:
    print("Last Christmas I gave you my heart")
    print("But the very next day you gave it away")
    print("This year, to save me from tears")
    print("I'll give it to someone special")
    print("Last Christmas I gave you my heart")
    print("But the very next day you gave it away")
    print("This year, to save me from tears")
    print("I'll give it to someone special")
if userPick == 9:
    print("Slip inside the eye of your mind")
    print("Don't you know you might find")
    print("A better place to play")
    print("You said that you'd never been")
    print("But all the things that you've seen")
    print("Will slowly fade away")
    print("So I'll start a revolution from my bed")
    print("Cause you said the brains I had went to my head")
    print("Step outside, summertime's in bloom")
    print("Stand up beside the fireplace")
    print("Take that look from off your face")
    print("You ain't ever gonna burn my heart out")
    print("And so Sally can wait")
    print("She knows it's too late as we're walking on by")
    print("Her soul slides away")
    print("But don't look back in anger")
    print("I heard you say")
if userPick == 10:
    print("Hold up")
    print("Hold on")
    print("Don't be scared")
    print("You'll never change what's been and gone")
    print("May your smile")
    print("Shine on")
    print("Don't be scared")
    print("Your destiny may keep you warm")
    print("Cause all of the stars are fading away")
    print("Just try not to worry, you'll se them someday")
    print("Take what you need, and be on your way")
    print("And stop crying your heart out")
